on:
  workflow_dispatch:
  workflow_call:

name: ğŸ— Build

jobs:
  build:
    name: ğŸ›  Build
    if: |
      !startsWith(github.event.head_commit.message, 'ci:')
      && !startsWith(github.event.head_commit.message, 'ci(')
      && !startsWith(github.event.head_commit.message, 'style:')
      && !startsWith(github.event.head_commit.message, 'style(')      
    runs-on: ubuntu-latest
    steps:
      - name: ğŸŸ Checkout Git Repository
        id: checkout_repository_step 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: ğŸ§° Install Flutter Toolchain
        uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - name: ğŸ›  Build Website
        id: build_step
        run: |
          flutter build web --release 
      - name: â¬† Upload Website Artifact
        id: upload_website_step        
        uses: actions/upload-pages-artifact@v1
        with: 
          path: build/web      
